SELECT 
	PT.PARTY_ID,
	PER.FIRST_NAME,
	PER.LAST_NAME,
	PT.CREATED_DATE AS ENTRY_DATE,
	CM.INFO_STRING AS EMAIL,
	TN.CONTACT_NUMBER AS PHONE,
	PR.ROLE_TYPE_ID AS ROLE
FROM
	PARTY PT
JOIN PERSON PER
ON
	PT.PARTY_ID = PER.PARTY_ID
JOIN PARTY_ROLE PR
ON
	PT.PARTY_ID = PR.PARTY_ID
JOIN PARTY_CONTACT_MECH PCM
ON
	PT.PARTY_ID = PCM.PARTY_ID
JOIN CONTACT_MECH CM
ON
	PCM.CONTACT_MECH_ID = CM.CONTACT_MECH_ID
JOIN TELECOM_NUMBER TN
ON
	CM.CONTACT_MECH_ID = TN.CONTACT_MECH_ID
WHERE
	PR.ROLE_TYPE_ID = 'CUSTOMER'
	AND PT.CREATED_DATE BETWEEN '2023-06-01' AND '2023-06-30';
