SELECT
	SUM(OH.GRAND_TOTAL) AS TOTAL_REVENUE,
	COUNT(OH.ORDER_ID) AS TOTAL_ORDERS
FROM
	SHIPMENT SP
JOIN ORDER_HEADER OH
ON
	SP.PRIMARY_ORDER_ID = OH.ORDER_ID
	AND SP.SHIPMENT_METHOD_TYPE_ID = 'STOREPICKUP'
WHERE
	OH.SALES_CHANNEL_ENUM_ID = 'WEB_SALES_CHANNEL';