SELECT
	SUM(OH.GRAND_TOTAL) AS TOTAL_REVENUE,
	COUNT(OH.ORDER_ID) AS TOTAL_ORDERS
FROM
	ORDER_HEADER OH
join
	shipment SP
ON
	SP.PRIMARY_ORDER_ID = OH.ORDER_ID
	AND SP.SHIPMENT_METHOD_TYPE_ID = 'STOREPICKUP'
	and OH.SALES_CHANNEL_ENUM_ID = 'WEB_SALES_CHANNEL';
