SELECT 
	OH.ORDER_ID ,
	OH.STATUS_ID ,
	OH.EXTERNAL_ID ,
	OH2.ORDER_HISTORY_ID ,
	OI.ORDER_ITEM_SEQ_ID ,
	OI.QUANTITY ,
	P.PRODUCT_ID ,
	P.PRODUCT_TYPE_ID ,
	P.INTERNAL_NAME ,
	OSG.SHIP_GROUP_SEQ_ID ,
	F.FACILITY_ID ,
	F.FACILITY_TYPE_ID ,
	F.PRODUCT_STORE_ID
FROM
	ORDER_HEADER OH
JOIN ORDER_STATUS OS
ON
	OS.STATUS_ID = 'ORDER_COMPLETED'
	AND OS.ORDER_ID = OH.ORDER_ID
	AND OS.STATUS_DATETIME BETWEEN '2023-08-01' AND '2023-08-31'
JOIN ORDER_HISTORY OH2
ON
	OH.ORDER_ID = OH2.ORDER_ID
JOIN ORDER_ITEM OI
ON
	OI.ORDER_ITEM_SEQ_ID = OH2.ORDER_ITEM_SEQ_ID
	AND OI.ORDER_ID = OH2.ORDER_ID
JOIN PRODUCT P
ON
	OI.PRODUCT_ID = P.PRODUCT_ID
JOIN ORDER_ITEM_SHIP_GROUP OSG
ON
	OH2.SHIP_GROUP_SEQ_ID = OSG.SHIP_GROUP_SEQ_ID
	AND OH2.ORDER_ID = OSG.ORDER_ID
JOIN FACILITY F
ON
	OSG.FACILITY_ID = F.FACILITY_ID
GROUP BY
	OH.ORDER_ID
