SELECT 
	P.PRODUCT_ID ,
	P.PRODUCT_NAME AS NAME,
	P.INTERNAL_NAME AS INTERNAL_NAME,
	GI.ID_VALUE AS NETSUITE_ID,
	P.PRODUCT_TYPE_ID ,
	GI.GOOD_IDENTIFICATION_TYPE_ID
FROM
	PRODUCT P
LEFT JOIN GOOD_IDENTIFICATION GI
ON
	P.PRODUCT_ID = GI.PRODUCT_ID
	AND GI.GOOD_IDENTIFICATION_TYPE_ID = 'NETSUITE_PRODUCT_ID'
WHERE
	GI.ID_VALUE IS NULL;
