SELECT
	DISTINCT 
	P.PRODUCT_ID AS PRODUCT_ID,
	P.PRODUCT_NAME ,
	MAX(CASE WHEN GI.GOOD_IDENTIFICATION_TYPE_ID = 'SHOPIFY_PROD_ID' THEN GI.ID_VALUE END) AS SHOPIFY_ID,
	MAX(CASE WHEN GI.GOOD_IDENTIFICATION_TYPE_ID = 'NETSUITE_PRODUCT_ID' THEN GI.ID_VALUE END) AS NETSUITE_PRODUCT_ID,
	MAX(CASE WHEN GI.GOOD_IDENTIFICATION_TYPE_ID = 'SKU' THEN GI.ID_VALUE END) AS SKU,
	P.IS_VARIANT ,
	P.IS_VIRTUAL
FROM
	PRODUCT P
JOIN GOOD_IDENTIFICATION GI
ON
	P.PRODUCT_ID = GI.PRODUCT_ID
	AND GI.GOOD_IDENTIFICATION_TYPE_ID IN ('SHOPIFY_PROD_ID', 'NETSUITE_PRODUCT_ID', 'SKU')
GROUP BY
	P.PRODUCT_ID
